modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/valentin-marquez/is-typing/issues"
license = "MIT"

[[mods]]
modId = "istyping"
version = "${version}"
displayName = "is Typing"
authors = "Nozz"
logoFile = "assets/istyping/icon.png"
description = '''
Lightweight typing indicator for Minecraft multiplayer that shows when other players are composing chat messages.
'''

[[dependencies.istyping]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.istyping]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.istyping]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
